export const data = [
 {
  customer_id: '1',
  first_name: 'Coby',
  last_name: 'Olondriz',
  email: 'john.doe@example.com',
  phone_number: '555-123-4567',
  address: {
   street: '123 Main St',
   city: 'Anytown',
   state: 'CA',
   zip_code: '90210',
  },
  plan: 'Unlimited',
  account_balance: 45.67,
 },
 {
  customer_id: '2',
  first_name: 'Jane',
  last_name: 'Smith',
  email: 'jane.smith@example.com',
  phone_number: '555-987-6543',
  address: {
   street: '456 Oak St',
   city: 'Othertown',
   state: 'NY',
   zip_code: '10001',
  },
  plan: 'Family',
  account_balance: 78.9,
 },
 {
  customer_id: '3',
  first_name: 'Alice',
  last_name: 'Johnson',
  email: 'alice.johnson@example.com',
  phone_number: '555-555-5555',
  address: {
   street: '789 Pine St',
   city: 'Sometown',
   state: 'TX',
   zip_code: '73301',
  },
  plan: 'Prepaid',
  account_balance: 12.34,
 },
 {
  customer_id: '4',
  first_name: 'Bob',
  last_name: 'Brown',
  email: 'bob.brown@example.com',
  phone_number: '555-444-3333',
  address: {
   street: '321 Elm St',
   city: 'Anycity',
   state: 'FL',
   zip_code: '33101',
  },
  plan: 'Unlimited',
  account_balance: 23.45,
 },
 {
  customer_id: '5',
  first_name: 'Carol',
  last_name: 'Davis',
  email: 'carol.davis@example.com',
  phone_number: '555-222-1111',
  address: {
   street: '654 Maple St',
   city: 'Newcity',
   state: 'IL',
   zip_code: '60601',
  },
  plan: 'Family',
  account_balance: 56.78,
 },
 {
  customer_id: '6',
  first_name: 'Eve',
  last_name: 'Miller',
  email: 'eve.miller@example.com',
  phone_number: '555-666-7777',
  address: {
   street: '987 Birch St',
   city: 'Oldtown',
   state: 'WA',
   zip_code: '98101',
  },
  plan: 'Prepaid',
  account_balance: 34.56,
 },
];
